<?php 

$options['options'] = array(
	'headerlayout' => 'pptclassic',
	'header_bg_color_bind' => 'on',
	'masthead_border_top_color' => '#000000',
	'masthead_border_top_style' => 'solid',
	'masthead_border_bottom_color' => '#000000',
	'masthead_border_bottom_style' => 'solid',
	'masthead_display' => 'static',
	'cache_buster' => '?83582',
	'biopic_align' => 'right',
	'bio_bg' => 'color',
	'bio_bg_color' => '#ffffff',
	'bio_border_style' => 'dotted',
	'header_bg_color' => '#ffffff',
	'nav_bg_color' => '#ffffff',
	'nav_dropdown_bg_color_bind' => 'on',
	'nav_dropdown_bg_color' => '#eaeaea',
	'nav_rss' => 'off',
	'nav_search_dropdown' => 'off',
	'nav_dropdown_opacity' => '100',
	'nav_align' => 'right',
	'nav_border_top_color' => '#000000',
	'nav_border_top_style' => 'solid',
	'nav_border_bottom_color' => '#000000',
	'nav_border_bottom_style' => 'solid',
	'contactform_yesno' => 'no',
	'gen_font_weight' => '400',
	'gen_font_style' => 'normal',
	'gen_text_transform' => 'none',
	'gen_link_font_weight' => '400',
	'gen_link_text_transform' => 'none',
	'gen_link_font_color_bind' => 'on',
	'gen_link_font_color' => '#0c29ad',
	'gen_link_visited_font_color_bind' => 'on',
	'gen_link_visited_font_color' => '#5a0bad',
	'header_font_family' => 'Arial, Helvetica, sans-serif',
	'header_font_weight' => '400',
	'header_font_style' => 'normal',
	'header_font_color' => '#0c29ad',
	'blog_border' => 'dropshadow',
	'blog_border_shadow_width' => 'narrow',
	'prophoto_classic_bar' => 'on',
	'prophoto_classic_bar_color' => '#000000',
	'comments_layout' => 'minima',
	'comments_area_border_style' => 'solid',
	'comments_header_link_font_size' => '11',
	'comments_header_link_font_family' => 'Arial, Helvetica, sans-serif',
	'comments_show_hide_method' => 'text',
	'comments_post_interact_spacing' => '15',
	'comments_emailafriend_subject' => 'ProPhoto 3 Dev',
	'comments_comment_timestamp_font_color' => '#000000',
	'footer_bg_color' => '#f0f0f0',
	'footer_headings_font_color' => '#666666',
	'comments_header_bg_img_repeat' => 'repeat',
	'comments_header_bg_img_position' => 'top left',
	'biopic_border_width' => '0',
	'nav_link_font_color_bind' => '',
	'comments_area_border_width' => '0',
);

$options['images'] = array(
	'logo' => 'prophoto1_logo.jpg',
	'masthead_image1' => 'prophoto1_masthead_image1.jpg',
	'biopic1' => 'prophoto1_biopic1.jpg',
);



 ?>